version: '3.8'

services:
  drupal:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./settings.php:/sites/default/settings.php
    environment:
      - DRUPAL_DATABASE_HOST=db.heady.internal
      - DRUPAL_DATABASE_NAME=drupal
      - DRUPAL_DATABASE_USER=admin
      - DRUPAL_DATABASE_PASSWORD=admin
    depends_on:
      - db
    networks:
      - heady-network

  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=drupal
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - drupal-db-data:/var/lib/mysql
    networks:
      - heady-network

networks:
  heady-network:
    driver: bridge
    name: heady-internal-network

volumes:
  drupal-db-data:
